### PR TITLE
ngDisabled bugfix

### LINKED ISSUE #134: angular-chosen won't disable with dynamic list of options (ng-options)
When using ng-options in the chosen directive it appears that the disable functionality doesn't work.

Please see this plnkr: http://plnkr.co/It5mNWOfyPI8BWNV72Kd

The plunk contains a chosen select list with static options, which does disable and a list with dynamic options using ng-options which does not.

I believe the problem lies in the stopLoading function of the directive. It always sets the disable property to false when calling it. overriding the ng-disable value.

Thanks,

### PR DESCRIPTION
**Pull request by 4simple**
There is a bug in stopLoading to set attr disabled as false.

It can fix #134.

### CODE REVIEW

**Comment by portus84** [comment]
+1

**Comment by lpsBetty** [comment]
+1

**Comment by lpsBetty** [comment]
why is this not merged?

**Comment by tiwarisnehal** [comment]
+1

**Comment by leocaseiro** [comment]
The #117 fix same issue

**Pull request closed without merging**
