### PR TITLE
Fixed bug calling trigger before DOM is loaded (AngularJS 1.3)

### LINKED ISSUE #82: the dropdown doesn't refresh after a promise is updated with value.
I tried to use promise and the drop down list says "no result" even after the result is comback. 
I tested with this sample code:

                    simulateAjax = function(result) {
                        var deferred, fn;

                        deferred = $q.defer();
                        fn = function() {
                            return deferred.resolve(result);
                        };
                        $timeout(fn, 3000);
                        return deferred.promise;
                    };
                    simulateAjax(['grooo', 'wowowowow', 'lakakalakakl', 'yadayada', 'insight', 'delve', 'synergy'])
                        .then(function(result) {
                            scope.optionsFromQuery = result;
                    });

### PR DESCRIPTION
**Pull request by gaui**
fixes #82

### CODE REVIEW

**Comment by gaui** [comment]
How about merging it then? You realize there are plenty of people using this plugin, but it's not behaving correctly because of this bug when used with AngularJS 1.3. If you're not going to continue updating this (last release March '14) we have no other option than forking it and continuing on our own.

**Comment by lpsBetty** [comment]
Can you please update the bower package too?

**Comment by pkarl** [comment]
@lpsBetty I just bump us to 1.0.7, bower should be able to sniff that out now

**Comment by lpsBetty** [comment]
thank you very much :+1:

**Comment by gaui** [comment]
Thank you so much! :+1:

**Pull request merged**
